name: Carbonoz Solarpilot
version: dev
slug: solarpilot
description: Integrated development environment tailored for Carbonoz Solarpilot system.
url: https://github.com/carbonoz-addons/addon-solarpilot
maintainer: carbonoz@carbonoz.com
ingress: true
ingress_port: 4000
ingress_stream: true
panel_icon: mdi:solar-panel-large
startup: services
init: false
arch:
  - aarch64
  - amd64
uart: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
services:
  - mysql:want
  - mqtt:want
options:
  packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  config_path: str?
  packages:
    - str
  init_commands:
    - str
